// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVwTayXxf-UsWdY6aBJPOuBXW1HBo_Kv8',
    appId: '1:614955091401:web:850e0f46172d0fd4801418',
    messagingSenderId: '614955091401',
    projectId: 'elearning-caf76',
    authDomain: 'elearning-caf76.firebaseapp.com',
    storageBucket: 'elearning-caf76.firebasestorage.app',
    measurementId: 'G-5S72F72CSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPg-paSZnDaTt2rOvB-9jtpBcVB5U8zcQ',
    appId: '1:614955091401:android:2ba6b7bcf5e8e63e801418',
    messagingSenderId: '614955091401',
    projectId: 'elearning-caf76',
    storageBucket: 'elearning-caf76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJBFFh_txbJrRh_2OfGEjfAh6I6r_R360',
    appId: '1:614955091401:ios:06353832f35c097d801418',
    messagingSenderId: '614955091401',
    projectId: 'elearning-caf76',
    storageBucket: 'elearning-caf76.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJBFFh_txbJrRh_2OfGEjfAh6I6r_R360',
    appId: '1:614955091401:ios:06353832f35c097d801418',
    messagingSenderId: '614955091401',
    projectId: 'elearning-caf76',
    storageBucket: 'elearning-caf76.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVwTayXxf-UsWdY6aBJPOuBXW1HBo_Kv8',
    appId: '1:614955091401:web:31441540c0827e40801418',
    messagingSenderId: '614955091401',
    projectId: 'elearning-caf76',
    authDomain: 'elearning-caf76.firebaseapp.com',
    storageBucket: 'elearning-caf76.firebasestorage.app',
    measurementId: 'G-1J63R6CGHP',
  );
}
